### ISSUE TITLE
UPC-E detection skips valid UPC-E codes

### ISSUE THREAD

**Issue by scashin133** [ankane/barkick#3]
00985234 is a valid UPC-E barcode but the current GTIN library skips it because the 2nd digit is a 0.

![image of 00985234 upce code](https://barcode.tec-it.com/barcode.ashx?data=00985234&code=UPCE&multiplebarcodes=false&translate-esc=false&unit=Fit&dpi=96&imagetype=Gif&rotation=0&color=%23000000&bgcolor=%23ffffff&qunit=Mm&quiet=0)

Do you know why for the detection you ignored codes where the 2nd digit is a 0? I searched but couldn't find anything saying this was a valid way to differentiate the codes.

I'm happy to work on a fix, but would want to learn more about why the detection works the way it does today.

**Comment by ankane** [comment]
From the tests, looks like it was for Trader Joe's, which uses EAN-8. I think the issue is there may [not be a reliable way](https://www.quora.com/Given-an-8-digit-barcode-how-can-you-determine-whether-it-is-EAN8-or-UPCE) to tell if an 8-digit code is UPC-E or EAN-8. We probably need to pass this info from the scanner to Barkick for 8-digit codes.

**Comment by ankane** [comment]
You can now do `GTIN.new(code, type: :upc_e)` on master.

**Comment by ankane** [comment]
Pushed a new version as well - upgrade instructions here https://github.com/ankane/barkick#010
